#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export ANDROID_HOME=/Volumes/Data/wysa/android-sdk-macosx/
export FLUTTER_HOME=/Volumes/Data/wysa/flutter/

export PATH=$FLUTTER_HOME/bin:$ANDROID_HOME/platform-tools/:$PATH:/usr/local/bin
